/* automatically generated by rust-bindgen */

extern "C" {
    pub fn cublasHgemm(
        handle: cublasHandle_t,
        transa: cublasOperation_t,
        transb: cublasOperation_t,
        m: ::std::os::raw::c_int,
        n: ::std::os::raw::c_int,
        k: ::std::os::raw::c_int,
        alpha: *const __half,
        A: *const __half,
        lda: ::std::os::raw::c_int,
        B: *const __half,
        ldb: ::std::os::raw::c_int,
        beta: *const __half,
        C: *mut __half,
        ldc: ::std::os::raw::c_int,
    ) -> cublasStatus_t;
}
